//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Controller/InputsManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputsManager: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputsManager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputsManager"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""b6582bc2-efa9-4b90-99c8-ee4c514fca93"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""42f12fe0-05d1-44c9-b6aa-dda7a91a03a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""0c140d98-bb63-4d0f-928c-cb3fd629326d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""926f7410-086e-4dd2-b125-5075f4fe039a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""c5e47840-11f8-44f5-9347-1094e9bcb37d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""4268560f-54b8-41bf-b9bc-5ea915a019a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""884e49c8-8141-4e77-9a7e-db5fcdf1e323"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""6864d05e-12f0-4e1e-bfe9-50bf7675e217"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AccelTime"",
                    ""type"": ""Button"",
                    ""id"": ""f1bc9251-35aa-49b5-86a3-ef631ab25b7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89592789-c9a2-4559-9837-3f079eecbdb6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02664022-5e01-4f97-a420-b3ec227e377a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79e43cab-bd3f-484b-ae9b-c3413920a4d2"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""415738b2-6bb0-4bc6-9ef1-9bbe6b5e97b3"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b0928b3-9f07-4454-8a2a-25e8a482bcab"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b5f04b5-72f5-4bc2-b1b9-2b611f9feaed"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c859da61-0e0e-4761-ab21-dc8f62bb2139"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74eccc37-504d-46e4-b82b-162f7b074fd2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelTime"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_Click = m_InGame.FindAction("Click", throwIfNotFound: true);
        m_InGame_RightClick = m_InGame.FindAction("RightClick", throwIfNotFound: true);
        m_InGame_One = m_InGame.FindAction("One", throwIfNotFound: true);
        m_InGame_Two = m_InGame.FindAction("Two", throwIfNotFound: true);
        m_InGame_Three = m_InGame.FindAction("Three", throwIfNotFound: true);
        m_InGame_Four = m_InGame.FindAction("Four", throwIfNotFound: true);
        m_InGame_Five = m_InGame.FindAction("Five", throwIfNotFound: true);
        m_InGame_AccelTime = m_InGame.FindAction("AccelTime", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_Click;
    private readonly InputAction m_InGame_RightClick;
    private readonly InputAction m_InGame_One;
    private readonly InputAction m_InGame_Two;
    private readonly InputAction m_InGame_Three;
    private readonly InputAction m_InGame_Four;
    private readonly InputAction m_InGame_Five;
    private readonly InputAction m_InGame_AccelTime;
    public struct InGameActions
    {
        private @InputsManager m_Wrapper;
        public InGameActions(@InputsManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_InGame_Click;
        public InputAction @RightClick => m_Wrapper.m_InGame_RightClick;
        public InputAction @One => m_Wrapper.m_InGame_One;
        public InputAction @Two => m_Wrapper.m_InGame_Two;
        public InputAction @Three => m_Wrapper.m_InGame_Three;
        public InputAction @Four => m_Wrapper.m_InGame_Four;
        public InputAction @Five => m_Wrapper.m_InGame_Five;
        public InputAction @AccelTime => m_Wrapper.m_InGame_AccelTime;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @AccelTime.started += instance.OnAccelTime;
            @AccelTime.performed += instance.OnAccelTime;
            @AccelTime.canceled += instance.OnAccelTime;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @AccelTime.started -= instance.OnAccelTime;
            @AccelTime.performed -= instance.OnAccelTime;
            @AccelTime.canceled -= instance.OnAccelTime;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);
    public interface IInGameActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnAccelTime(InputAction.CallbackContext context);
    }
}
